language: c

matrix:
  include:
    # gcc 5
    - env: COMPILER=gcc-5
      os: linux
      addons: &gcc5
        apt:
          packages:
            - gcc-5
          sources:
            - ubuntu-toolchain-r-test

# less ancient environment
sudo: required
dist: trusty

# install cmocka for testing (we need never version)
before_install:
# overcome travis ignorance (we can't setup this directly in matrix)
  - export CC=$COMPILER
# setup cmocka
  - wget https://cmocka.org/files/1.0/cmocka-1.0.1.tar.xz
  - tar -xvf cmocka-1.0.1.tar.xz
  - cd cmocka-1.0.1
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ..
  - make
  - sudo make install
  - cd ../..

# test only structure shape
script: cd structure-shape && make test && ./shapeup_tests
