language: c

compiler:
  - clang
  - gcc

# setup cmocka
install:
  - wget https://cmocka.org/files/1.0/cmocka-1.0.1.tar.xz
  - tar -xvf cmocka-1.0.0.tar.xz
  - cd cmocka-1.0.0
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - sudo make install

# test only structure shape
script: cd structure-shape && make test && ./shapeup_tests
