language: c

matrix:
  include:
    # gcc 5
    - env: COMPILER=gcc-5
      os: linux
      addons: &gcc5
        apt:
          packages:
            - gcc-5
          sources:
            - ubuntu-toolchain-r-test

# less ancient environment
sudo: required
dist: trusty

# install cmocka for testing
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libcmocka-dev
# overcome travis ignorance (we can't setup this directly in matrix)
  - export CC=$COMPILER

# test only structure shape
script: cd structure-shape && make test && ./shapeup_tests
