language: c

compiler:
  - clang
  - gcc

# less ancient environment
sudo: required
dist: trusty

# install cmocka for testing
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libcmocka-dev

# test only structure shape
script: cd structure-shape && make test && ./shapeup_tests

