language: c

matrix:
  include:
    # Test gcc-5.0: C++11
    - env: GCC_VERSION=5 CPP=11 LIBCXX=Off
      os: linux
        apt:
          packages:
            - gcc-5
          sources:
            - ubuntu-toolchain-r-test

# less ancient environment
sudo: required
dist: trusty

# install cmocka for testing
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libcmocka-dev
  - export CC=gcc-5

# test only structure shape
script: cd structure-shape && make test && ./shapeup_tests

